spring boot version into 3.1.2 because ManualKafkaAndPostgresTestContainerApplicationTest in eats-order-application causes an error "Caused by: java.lang.NoSuchMethodError: 'void org.springframework.http.client.reactive.ReactorClientHttpConnector.<init>(org.springframework.http.client.reactive.ReactorResourceFactory, java.util.function.Function)' "