spring-kafka + confluenct kafka version conflict resolved. pom.xml setting for TestContainerTest.java.
IMPORTANT: spring-kafka contains apache kafka clients, stream. so remove them in pom.xml.

Solved Method not found error.

```
11:36:57.453 [kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Received error UNKNOWN_SERVER_ERROR from node -1 when making an ApiVersionsRequest with correlation id 3. Disconnecting.
11:36:57.961 [data-plane-kafka-request-handler-3] ERROR kafka.server.KafkaApis -- [KafkaApi-0] Unexpected error handling request RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=adminclient-1, correlationId=4, headerVersion=2) -- ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='3.5.1') with context RequestContext(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=adminclient-1, correlationId=4, headerVersion=2), connectionId='127.0.0.1:52455-127.0.0.1:52461-1', clientAddress=/127.0.0.1, principal=User:ANONYMOUS, listenerName=ListenerName(PLAINTEXT), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=unknown, softwareVersion=unknown), fromPrivilegedListener=true, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@3e171e37])
java.lang.NoSuchMethodError: 'org.apache.kafka.common.requests.ApiVersionsResponse org.apache.kafka.common.requests.ApiVersionsResponse.createApiVersionsResponse(int, org.apache.kafka.common.record.RecordVersion, org.apache.kafka.common.feature.Features, java.util.Map, long, org.apache.kafka.clients.NodeApiVersions, org.apache.kafka.common.message.ApiMessageType$ListenerType)'
    at kafka.server.DefaultApiVersionManager.apiVersionResponse(ApiVersionManager.scala:89)
    at kafka.server.KafkaApis.createResponseCallback$1(KafkaApis.scala:1832)
    at kafka.server.KafkaApis.$anonfun$handleApiVersionsRequest$1(KafkaApis.scala:1835)
    at kafka.server.KafkaApis.$anonfun$handleApiVersionsRequest$1$adapted(KafkaApis.scala:1835)
    at kafka.server.RequestHandlerHelper.sendResponseMaybeThrottle(RequestHandlerHelper.scala:128)
    at kafka.server.KafkaApis.handleApiVersionsRequest(KafkaApis.scala:1835)
    at kafka.server.KafkaApis.handle(KafkaApis.scala:201)
    at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:75)
    at java.base/java.lang.Thread.run(Thread.java:840)
```